# demo_engine.py
import re

def analyze_code_demo(input_text: str) -> str:
    # Basic rule-based engine for Demo Mode
    
    # 1. Hardcoded CUDA devices
    if "cuda:0" in input_text or "cuda" in input_text:
        return """## Summary
The code explicitly hardcodes `cuda:0` or `cuda` device strings.

## Detected ROCm issue
While PyTorch on ROCm aliases `cuda` to HIP under the hood, hardcoding `cuda:0` is an anti-pattern. If you have multiple GPUs or want to write portable code, it's better to dynamically check for available devices. On ROCm, `torch.cuda.is_available()` returns `True` if a HIP device is present.

## Recommended fix
Replace hardcoded `cuda:0` with dynamic device selection.

## Corrected code or config
```python
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# On AMD ROCm, torch.cuda is seamlessly translated to HIP.
```

## Verification commands
```bash
python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name(0))"
```

## ROCm readiness score
80/100. PyTorch handles `cuda` strings automatically on ROCm, but dynamic device selection is better.

## Cursor prompt
"Update the Python code to remove hardcoded `cuda:0` devices and use a dynamic `torch.device` selection that is compatible with PyTorch on AMD ROCm."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "nvidia-smi" in input_text:
        return """## Summary
The code attempts to run `nvidia-smi` to check GPU status.

## Detected ROCm issue
`nvidia-smi` is specific to NVIDIA drivers. On AMD GPUs, the equivalent tool is `rocm-smi`.

## Recommended fix
Change the subprocess call to use `rocm-smi`.

## Corrected code or config
```python
import subprocess

def check_gpu():
    try:
        subprocess.run(["rocm-smi"], check=True)
        print("AMD GPU is ready.")
    except Exception:
        print("No GPU found.")
```

## Verification commands
```bash
rocm-smi
```

## ROCm readiness score
0/100. The code will crash on AMD nodes with `FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'`.

## Cursor prompt
"Replace `nvidia-smi` calls with `rocm-smi` to make this script compatible with AMD ROCm environments."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    # Generic response
    return """## Summary
Code appears generic or requires deeper semantic analysis.

## Detected ROCm issue
No critical CUDA-specific anti-patterns detected via static rules.

## Recommended fix
Verify that your PyTorch installation is ROCm-compatible.

## Corrected code or config
No code change required.

## Verification commands
```bash
python -c "import torch; print(torch.version.hip)"
```

## ROCm readiness score
90/100. Looks clean.

## Cursor prompt
"Review this code for any implicit NVIDIA/CUDA dependencies that might break on AMD ROCm."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

def analyze_error_demo(input_text: str) -> str:
    if "No HIP GPUs are available" in input_text:
        return """## Summary
PyTorch cannot find any AMD GPUs, despite being built with ROCm support.

## Detected ROCm issue
The ROCm kernel drivers might not be loaded, the user might lack permissions to access the `/dev/kfd` device, or the GPU model is not officially supported by the current PyTorch ROCm build (requires `HSA_OVERRIDE_GFX_VERSION`).

## Recommended fix
1. Verify the GPU is detected by the OS.
2. Ensure your user is in the `render` and `video` groups.
3. If using an unsupported consumer GPU, set `HSA_OVERRIDE_GFX_VERSION`.

## Corrected code or config
No code change required.

## Verification commands
```bash
rocm-smi
groups
ls -l /dev/kfd
```

## ROCm readiness score
0/100. The application cannot start.

## Cursor prompt
"How do I add my Linux user to the `render` and `video` groups to access AMD GPUs for ROCm?"

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "HIP out of memory" in input_text:
        return """## Summary
The application has exhausted the available GPU memory on the AMD Instinct / Radeon accelerator.

## Detected ROCm issue
This is the HIP equivalent of the `CUDA out of memory` error. PyTorch's memory allocator on ROCm operates similarly to CUDA but may have slightly different fragmentation characteristics.

## Recommended fix
Reduce the batch size, enable gradient accumulation, or use techniques like flash attention. For LLM inference, consider using quantization or reducing the KV cache size (if using vLLM).

## Corrected code or config
No code change required. You must adjust hyper-parameters.

## Verification commands
```bash
export PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:128
```

## ROCm readiness score
50/100. Environment works, but configuration is sub-optimal.

## Cursor prompt
"How can I set the `PYTORCH_HIP_ALLOC_CONF` environment variable to optimize memory fragmentation for PyTorch on AMD GPUs?"

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    return """## Summary
Generic error analysis.

## Detected ROCm issue
Unknown runtime error.

## Recommended fix
Check ROCm compatibility matrix and ensure PyTorch ROCm version matches drivers.

## Corrected code or config
No code change required.

## Verification commands
```bash
dpkg -l | grep rocm
```

## ROCm readiness score
N/A

## Cursor prompt
"Analyze this ROCm traceback and suggest potential environmental causes."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

def analyze_env_demo(input_text: str) -> str:
    if "nvidia/cuda" in input_text:
        return """## Summary
The Dockerfile uses an NVIDIA CUDA base image.

## Detected ROCm issue
NVIDIA base images contain CUDA toolkits that do not work on AMD hardware. ROCm workloads require `rocm/pytorch` or ubuntu bases with ROCm installed.

## Recommended fix
Switch the base image to the official ROCm PyTorch Docker image.

## Corrected code or config
```dockerfile
FROM rocm/pytorch:rocm6.1.2_ubuntu22.04_py3.10_pytorch_2.1.2

RUN apt-get update && apt-get install -y python3-pip
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["python3", "app.py"]
```

## Verification commands
```bash
docker run -it --device=/dev/kfd --device=/dev/dri --group-add=video rocm/pytorch:rocm6.1.2_ubuntu22.04_py3.10_pytorch_2.1.2 rocm-smi
```

## ROCm readiness score
0/100. The original Dockerfile will fail to utilize AMD GPUs.

## Cursor prompt
"Update this Dockerfile to use the official `rocm/pytorch` base image and ensure all NVIDIA-specific apt packages are removed."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "bitsandbytes" in input_text or "+cu" in input_text:
        return """## Summary
The requirements file requests CUDA-specific python packages.

## Detected ROCm issue
Packages like `torch==2.0.1+cu118` download precompiled CUDA binaries. `bitsandbytes` historically required special ROCm builds or newer versions for AMD support. `flash-attn` requires ROCm-specific wheels or compilation from source.

## Recommended fix
Change the PyTorch index URL to point to ROCm wheels. Update `bitsandbytes` to >= 0.43.0 which has native multi-backend support. Use ROCm-compiled `flash-attn` wheels.

## Corrected code or config
```text
--extra-index-url https://download.pytorch.org/whl/rocm6.1
torch==2.3.0+rocm6.1
torchvision==0.18.0+rocm6.1
bitsandbytes>=0.43.0
```

## Verification commands
```bash
pip show torch | grep Version
python -c "import bitsandbytes; print('bitsandbytes loaded successfully')"
```

## ROCm readiness score
10/100. Dependencies are tightly coupled to CUDA.

## Cursor prompt
"Rewrite this `requirements.txt` to install the ROCm version of PyTorch and update bitsandbytes/flash-attn to their ROCm-compatible versions."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    return """## Summary
Generic Docker/Env file.

## Detected ROCm issue
Ensure no underlying C++ extensions assume nvcc compiler.

## Recommended fix
Use ROCm compatible base image.

## Corrected code or config
No code change required.

## Verification commands
```bash
hipcc --version
```

## ROCm readiness score
70/100.

## Cursor prompt
"Check this setup for any hidden NVIDIA nvcc compiler dependencies."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""
