# demo_engine.py
import re

def analyze_code_demo(input_text: str) -> str:
    # Basic rule-based engine for Demo Mode
    
    # 1. Hardcoded CUDA devices
    if "cuda:0" in input_text or "cuda" in input_text:
        return """## Summary
The code explicitly hardcodes `cuda:0` or `cuda` device strings.

## Detected ROCm issue
While PyTorch on ROCm aliases `cuda` to HIP under the hood, hardcoding `cuda:0` is an anti-pattern. If you have multiple GPUs or want to write portable code, it's better to dynamically check for available devices. On ROCm, `torch.cuda.is_available()` returns `True` if a HIP device is present.

## Recommended fix
Replace hardcoded `cuda:0` with dynamic device selection.

## Corrected code or config
```python
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# On AMD ROCm, torch.cuda is seamlessly translated to HIP.
```

## Verification commands
```bash
python -c "import torch; print(torch.cuda.is_available()); print(torch.cuda.get_device_name(0))"
```

## ROCm readiness score
80/100. PyTorch handles `cuda` strings automatically on ROCm, but dynamic device selection is better.

## Cursor prompt
"Update the Python code to remove hardcoded `cuda:0` devices and use a dynamic `torch.device` selection that is compatible with PyTorch on AMD ROCm."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "nvidia-smi" in input_text:
        return """## Summary
The code attempts to run `nvidia-smi` to check GPU status.

## Detected ROCm issue
`nvidia-smi` and its query flags are specific to NVIDIA drivers. Current ROCm
documentation recommends AMD SMI; older deployments may still provide ROCm SMI.

## Recommended fix
Use the management CLI installed in the target ROCm release and adapt parsing to its
documented output. Do not assume NVIDIA CSV flags are portable.

## Corrected code or config
```python
import subprocess

def check_gpu():
    try:
        subprocess.run(["amd-smi", "list"], check=True)
        print("AMD GPU is ready.")
    except Exception:
        print("No GPU found.")
```

## Verification commands
```bash
amd-smi list
rocminfo
```

## ROCm readiness score
0/100. The code will crash on AMD nodes with `FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'`.

## Cursor prompt
"Replace this NVIDIA health check with an AMD SMI collector and update its output parser for the deployed ROCm version."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    # Generic response
    return """## Summary
Code appears generic or requires deeper semantic analysis.

## Detected ROCm issue
No critical CUDA-specific anti-patterns detected via static rules.

## Recommended fix
Verify that your PyTorch installation is ROCm-compatible.

## Corrected code or config
No code change required.

## Verification commands
```bash
python -c "import torch; print(torch.version.hip)"
```

## ROCm readiness score
90/100. Looks clean.

## Cursor prompt
"Review this code for any implicit NVIDIA/CUDA dependencies that might break on AMD ROCm."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

def analyze_error_demo(input_text: str) -> str:
    if "No HIP GPUs are available" in input_text:
        return """## Summary
PyTorch cannot find any AMD GPUs, despite being built with ROCm support.

## Detected ROCm issue
The ROCm kernel driver might not be loaded, the user might lack permission to access
`/dev/kfd` and the render nodes, or the installed PyTorch/ROCm build might not support
the host GPU.

## Recommended fix
1. Verify the GPU is detected by the OS.
2. Ensure your user is in the `render` and `video` groups.
3. Check the official compatibility matrix for the exact GPU, OS, ROCm, and PyTorch versions.

## Corrected code or config
No code change required.

## Verification commands
```bash
rocminfo
amd-smi list
groups
ls -l /dev/kfd
```

## ROCm readiness score
0/100. The application cannot start.

## Cursor prompt
"How do I add my Linux user to the `render` and `video` groups to access AMD GPUs for ROCm?"

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "HIP out of memory" in input_text:
        return """## Summary
The application has exhausted the available GPU memory on the AMD Instinct / Radeon accelerator.

## Detected ROCm issue
This is the HIP equivalent of the `CUDA out of memory` error. PyTorch's memory allocator on ROCm operates similarly to CUDA but may have slightly different fragmentation characteristics.

## Recommended fix
Measure live tensor memory and allocator-reserved memory first. Then reduce batch size,
activation storage, retained tensor references, or inference KV-cache size as the
measured workload requires.

## Corrected code or config
No code change required. You must adjust hyper-parameters.

## Verification commands
```bash
python -c "import torch; print(torch.cuda.memory_summary() if torch.cuda.is_available() else 'no GPU')"
```

## ROCm readiness score
50/100. Environment works, but configuration is sub-optimal.

## Cursor prompt
"Profile `memory_allocated`, `memory_reserved`, and tensor lifetimes for this ROCm PyTorch OOM before changing allocator settings."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    return """## Summary
Generic error analysis.

## Detected ROCm issue
Unknown runtime error.

## Recommended fix
Check ROCm compatibility matrix and ensure PyTorch ROCm version matches drivers.

## Corrected code or config
No code change required.

## Verification commands
```bash
rocminfo
python -c "import torch; print(torch.__version__, torch.version.hip)"
```

## ROCm readiness score
N/A

## Cursor prompt
"Analyze this ROCm traceback and suggest potential environmental causes."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

def analyze_env_demo(input_text: str) -> str:
    if "nvidia/cuda" in input_text:
        return """## Summary
The Dockerfile uses an NVIDIA CUDA base image.

## Detected ROCm issue
NVIDIA base images contain CUDA toolkits that do not work on AMD hardware. ROCm workloads require `rocm/pytorch` or ubuntu bases with ROCm installed.

## Recommended fix
Select an official ROCm PyTorch image tag that is compatible with the host driver,
GPU, Python, and required framework versions.

## Corrected code or config
```dockerfile
FROM rocm/pytorch:<verified-compatible-tag>

RUN apt-get update && apt-get install -y python3-pip
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["python3", "app.py"]
```

## Verification commands
```bash
docker run --rm --device=/dev/kfd --device=/dev/dri <image> rocminfo
```

## ROCm readiness score
0/100. The original Dockerfile will fail to utilize AMD GPUs.

## Cursor prompt
"Update this Dockerfile to use the official `rocm/pytorch` base image and ensure all NVIDIA-specific apt packages are removed."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    if "bitsandbytes" in input_text or "+cu" in input_text:
        return """## Summary
The requirements file requests CUDA-specific python packages.

## Detected ROCm issue
Packages such as `torch==2.0.1+cu118` select CUDA binaries. Compatibility of compiled
extensions such as `bitsandbytes`, `flash-attn`, and `xformers` depends on their exact
release, PyTorch/ROCm versions, wheel platform, and GPU architecture.

## Recommended fix
Select PyTorch using its official ROCm installation matrix. For each compiled
extension, use only a documented compatible wheel or a reproducible source build and
test a representative operation.

## Corrected code or config
```text
# Pin versions only after selecting a supported ROCm/PyTorch combination.
# Do not carry CUDA-only +cu wheel suffixes into the ROCm environment.
```

## Verification commands
```bash
python -c "import torch; print(torch.__version__, torch.version.hip)"
python -m pip check
```

## ROCm readiness score
10/100. Dependencies are tightly coupled to CUDA.

## Cursor prompt
"Check every compiled dependency against the official support matrix for the target ROCm/PyTorch stack; do not guess replacement versions."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""

    return """## Summary
Generic Docker/Env file.

## Detected ROCm issue
Ensure no underlying C++ extensions assume nvcc compiler.

## Recommended fix
Use ROCm compatible base image.

## Corrected code or config
No code change required.

## Verification commands
```bash
hipcc --version
```

## ROCm readiness score
70/100.

## Cursor prompt
"Check this setup for any hidden NVIDIA nvcc compiler dependencies."

## Notes and limitations
This output is migration guidance generated by ROCmPilot's deterministic demo mode. Always test generated changes in your target ROCm environment.
"""
